name: customer_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http:
  shared_preferences:
  get:
  flutter_screenutil:
  flutter_svg:
  rename:
  intl:
  fl_chart: ^0.68.0
  device_preview:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

#for app logo
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Product-Sans-Italic.ttf
          weight: 400
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
